<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/menu/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.menu.'), function () {

Route::get('menus', ['as'=> 'menus.index', 'uses' => 'Menu\MenuController@index']);
Route::post('menus', ['as'=> 'menus.store', 'uses' => 'Menu\MenuController@store']);
Route::get('menus/create', ['as'=> 'menus.create', 'uses' => 'Menu\MenuController@create']);
Route::put('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::patch('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::get('menus/{id}/delete', array('as' => 'menus.delete', 'uses' => 'Menu\MenuController@getDelete'));
Route::get('menus/{id}/confirm-delete', array('as' => 'menus.confirm-delete', 'uses' => 'Menu\MenuController@getModalDelete'));
Route::get('menus/{menus}', ['as'=> 'menus.show', 'uses' => 'Menu\MenuController@show']);
Route::get('menus/{menus}/edit', ['as'=> 'menus.edit', 'uses' => 'Menu\MenuController@edit']);

});


Route::group(array('prefix' => 'admin/menu/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.menu.'), function () {

Route::get('menus', ['as'=> 'menus.index', 'uses' => 'Menu\MenuController@index']);
Route::post('menus', ['as'=> 'menus.store', 'uses' => 'Menu\MenuController@store']);
Route::get('menus/create', ['as'=> 'menus.create', 'uses' => 'Menu\MenuController@create']);
Route::put('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::patch('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::get('menus/{id}/delete', array('as' => 'menus.delete', 'uses' => 'Menu\MenuController@getDelete'));
Route::get('menus/{id}/confirm-delete', array('as' => 'menus.confirm-delete', 'uses' => 'Menu\MenuController@getModalDelete'));
Route::get('menus/{menus}', ['as'=> 'menus.show', 'uses' => 'Menu\MenuController@show']);
Route::get('menus/{menus}/edit', ['as'=> 'menus.edit', 'uses' => 'Menu\MenuController@edit']);

});


Route::group(array('prefix' => 'admin/produit/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.produit.'), function () {

Route::get('produits', ['as'=> 'produits.index', 'uses' => 'Produit\ProduitController@index']);
Route::post('produits', ['as'=> 'produits.store', 'uses' => 'Produit\ProduitController@store']);
Route::get('produits/create', ['as'=> 'produits.create', 'uses' => 'Produit\ProduitController@create']);
Route::put('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::patch('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::get('produits/{id}/delete', array('as' => 'produits.delete', 'uses' => 'Produit\ProduitController@getDelete'));
Route::get('produits/{id}/confirm-delete', array('as' => 'produits.confirm-delete', 'uses' => 'Produit\ProduitController@getModalDelete'));
Route::get('produits/{produits}', ['as'=> 'produits.show', 'uses' => 'Produit\ProduitController@show']);
Route::get('produits/{produits}/edit', ['as'=> 'produits.edit', 'uses' => 'Produit\ProduitController@edit']);

});
