<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/menu/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.menu.'), function () {

Route::get('menus', ['as'=> 'menus.index', 'uses' => 'Menu\MenuController@index']);
Route::post('menus', ['as'=> 'menus.store', 'uses' => 'Menu\MenuController@store']);
Route::get('menus/create', ['as'=> 'menus.create', 'uses' => 'Menu\MenuController@create']);
Route::put('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::patch('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::get('menus/{id}/delete', array('as' => 'menus.delete', 'uses' => 'Menu\MenuController@getDelete'));
Route::get('menus/{id}/confirm-delete', array('as' => 'menus.confirm-delete', 'uses' => 'Menu\MenuController@getModalDelete'));
Route::get('menus/{menus}', ['as'=> 'menus.show', 'uses' => 'Menu\MenuController@show']);
Route::get('menus/{menus}/edit', ['as'=> 'menus.edit', 'uses' => 'Menu\MenuController@edit']);

});


Route::group(array('prefix' => 'admin/menu/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.menu.'), function () {

Route::get('menus', ['as'=> 'menus.index', 'uses' => 'Menu\MenuController@index']);
Route::post('menus', ['as'=> 'menus.store', 'uses' => 'Menu\MenuController@store']);
Route::get('menus/create', ['as'=> 'menus.create', 'uses' => 'Menu\MenuController@create']);
Route::put('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::patch('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::get('menus/{id}/delete', array('as' => 'menus.delete', 'uses' => 'Menu\MenuController@getDelete'));
Route::get('menus/{id}/confirm-delete', array('as' => 'menus.confirm-delete', 'uses' => 'Menu\MenuController@getModalDelete'));
Route::get('menus/{menus}', ['as'=> 'menus.show', 'uses' => 'Menu\MenuController@show']);
Route::get('menus/{menus}/edit', ['as'=> 'menus.edit', 'uses' => 'Menu\MenuController@edit']);

});


Route::group(array('prefix' => 'admin/produit/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.produit.'), function () {

Route::get('produits', ['as'=> 'produits.index', 'uses' => 'Produit\ProduitController@index']);
Route::post('produits', ['as'=> 'produits.store', 'uses' => 'Produit\ProduitController@store']);
Route::get('produits/create', ['as'=> 'produits.create', 'uses' => 'Produit\ProduitController@create']);
Route::put('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::patch('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::get('produits/{id}/delete', array('as' => 'produits.delete', 'uses' => 'Produit\ProduitController@getDelete'));
Route::get('produits/{id}/confirm-delete', array('as' => 'produits.confirm-delete', 'uses' => 'Produit\ProduitController@getModalDelete'));
Route::get('produits/{produits}', ['as'=> 'produits.show', 'uses' => 'Produit\ProduitController@show']);
Route::get('produits/{produits}/edit', ['as'=> 'produits.edit', 'uses' => 'Produit\ProduitController@edit']);

});


Route::group(array('prefix' => 'admin/table/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.table.'), function () {

Route::get('tables', ['as'=> 'tables.index', 'uses' => 'Table\TableController@index']);
Route::post('tables', ['as'=> 'tables.store', 'uses' => 'Table\TableController@store']);
Route::get('tables/create', ['as'=> 'tables.create', 'uses' => 'Table\TableController@create']);
Route::put('tables/{tables}', ['as'=> 'tables.update', 'uses' => 'Table\TableController@update']);
Route::patch('tables/{tables}', ['as'=> 'tables.update', 'uses' => 'Table\TableController@update']);
Route::get('tables/{id}/delete', array('as' => 'tables.delete', 'uses' => 'Table\TableController@getDelete'));
Route::get('tables/{id}/confirm-delete', array('as' => 'tables.confirm-delete', 'uses' => 'Table\TableController@getModalDelete'));
Route::get('tables/{tables}', ['as'=> 'tables.show', 'uses' => 'Table\TableController@show']);
Route::get('tables/{tables}/edit', ['as'=> 'tables.edit', 'uses' => 'Table\TableController@edit']);

});


Route::group(array('prefix' => 'admin/client/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.client.'), function () {

Route::get('clients', ['as'=> 'clients.index', 'uses' => 'Client\ClientController@index']);
Route::post('clients', ['as'=> 'clients.store', 'uses' => 'Client\ClientController@store']);
Route::get('clients/create', ['as'=> 'clients.create', 'uses' => 'Client\ClientController@create']);
Route::put('clients/{clients}', ['as'=> 'clients.update', 'uses' => 'Client\ClientController@update']);
Route::patch('clients/{clients}', ['as'=> 'clients.update', 'uses' => 'Client\ClientController@update']);
Route::get('clients/{id}/delete', array('as' => 'clients.delete', 'uses' => 'Client\ClientController@getDelete'));
Route::get('clients/{id}/confirm-delete', array('as' => 'clients.confirm-delete', 'uses' => 'Client\ClientController@getModalDelete'));
Route::get('clients/{clients}', ['as'=> 'clients.show', 'uses' => 'Client\ClientController@show']);
Route::get('clients/{clients}/edit', ['as'=> 'clients.edit', 'uses' => 'Client\ClientController@edit']);

});


Route::group(array('prefix' => 'admin/menu/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.menu.'), function () {

Route::get('menus', ['as'=> 'menus.index', 'uses' => 'Menu\MenuController@index']);
Route::post('menus', ['as'=> 'menus.store', 'uses' => 'Menu\MenuController@store']);
Route::get('menus/create', ['as'=> 'menus.create', 'uses' => 'Menu\MenuController@create']);
Route::put('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::patch('menus/{menus}', ['as'=> 'menus.update', 'uses' => 'Menu\MenuController@update']);
Route::get('menus/{id}/delete', array('as' => 'menus.delete', 'uses' => 'Menu\MenuController@getDelete'));
Route::get('menus/{id}/confirm-delete', array('as' => 'menus.confirm-delete', 'uses' => 'Menu\MenuController@getModalDelete'));
Route::get('menus/{menus}', ['as'=> 'menus.show', 'uses' => 'Menu\MenuController@show']);
Route::get('menus/{menus}/edit', ['as'=> 'menus.edit', 'uses' => 'Menu\MenuController@edit']);

});


Route::group(array('prefix' => 'admin/produit/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.produit.'), function () {

Route::get('produits', ['as'=> 'produits.index', 'uses' => 'Produit\ProduitController@index']);
Route::post('produits', ['as'=> 'produits.store', 'uses' => 'Produit\ProduitController@store']);
Route::get('produits/create', ['as'=> 'produits.create', 'uses' => 'Produit\ProduitController@create']);
Route::put('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::patch('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::get('produits/{id}/delete', array('as' => 'produits.delete', 'uses' => 'Produit\ProduitController@getDelete'));
Route::get('produits/{id}/confirm-delete', array('as' => 'produits.confirm-delete', 'uses' => 'Produit\ProduitController@getModalDelete'));
Route::get('produits/{produits}', ['as'=> 'produits.show', 'uses' => 'Produit\ProduitController@show']);
Route::get('produits/{produits}/edit', ['as'=> 'produits.edit', 'uses' => 'Produit\ProduitController@edit']);

});


Route::group(array('prefix' => 'admin/produit/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.produit.'), function () {

Route::get('produits', ['as'=> 'produits.index', 'uses' => 'Produit\ProduitController@index']);
Route::post('produits', ['as'=> 'produits.store', 'uses' => 'Produit\ProduitController@store']);
Route::get('produits/create', ['as'=> 'produits.create', 'uses' => 'Produit\ProduitController@create']);
Route::put('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::patch('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::get('produits/{id}/delete', array('as' => 'produits.delete', 'uses' => 'Produit\ProduitController@getDelete'));
Route::get('produits/{id}/confirm-delete', array('as' => 'produits.confirm-delete', 'uses' => 'Produit\ProduitController@getModalDelete'));
Route::get('produits/{produits}', ['as'=> 'produits.show', 'uses' => 'Produit\ProduitController@show']);
Route::get('produits/{produits}/edit', ['as'=> 'produits.edit', 'uses' => 'Produit\ProduitController@edit']);

});


Route::group(array('prefix' => 'admin/produit/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.produit.'), function () {

Route::get('produits', ['as'=> 'produits.index', 'uses' => 'Produit\ProduitController@index']);
Route::post('produits', ['as'=> 'produits.store', 'uses' => 'Produit\ProduitController@store']);
Route::get('produits/create', ['as'=> 'produits.create', 'uses' => 'Produit\ProduitController@create']);
Route::put('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::patch('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::get('produits/{id}/delete', array('as' => 'produits.delete', 'uses' => 'Produit\ProduitController@getDelete'));
Route::get('produits/{id}/confirm-delete', array('as' => 'produits.confirm-delete', 'uses' => 'Produit\ProduitController@getModalDelete'));
Route::get('produits/{produits}', ['as'=> 'produits.show', 'uses' => 'Produit\ProduitController@show']);
Route::get('produits/{produits}/edit', ['as'=> 'produits.edit', 'uses' => 'Produit\ProduitController@edit']);

});


Route::group(array('prefix' => 'admin/produit/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.produit.'), function () {

Route::get('produits', ['as'=> 'produits.index', 'uses' => 'Produit\ProduitController@index']);
Route::post('produits', ['as'=> 'produits.store', 'uses' => 'Produit\ProduitController@store']);
Route::get('produits/create', ['as'=> 'produits.create', 'uses' => 'Produit\ProduitController@create']);
Route::put('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::patch('produits/{produits}', ['as'=> 'produits.update', 'uses' => 'Produit\ProduitController@update']);
Route::get('produits/{id}/delete', array('as' => 'produits.delete', 'uses' => 'Produit\ProduitController@getDelete'));
Route::get('produits/{id}/confirm-delete', array('as' => 'produits.confirm-delete', 'uses' => 'Produit\ProduitController@getModalDelete'));
Route::get('produits/{produits}', ['as'=> 'produits.show', 'uses' => 'Produit\ProduitController@show']);
Route::get('produits/{produits}/edit', ['as'=> 'produits.edit', 'uses' => 'Produit\ProduitController@edit']);

});


Route::group(array('prefix' => 'admin/table/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.table.'), function () {

Route::get('tables', ['as'=> 'tables.index', 'uses' => 'Table\TableController@index']);
Route::post('tables', ['as'=> 'tables.store', 'uses' => 'Table\TableController@store']);
Route::get('tables/create', ['as'=> 'tables.create', 'uses' => 'Table\TableController@create']);
Route::put('tables/{tables}', ['as'=> 'tables.update', 'uses' => 'Table\TableController@update']);
Route::patch('tables/{tables}', ['as'=> 'tables.update', 'uses' => 'Table\TableController@update']);
Route::get('tables/{id}/delete', array('as' => 'tables.delete', 'uses' => 'Table\TableController@getDelete'));
Route::get('tables/{id}/confirm-delete', array('as' => 'tables.confirm-delete', 'uses' => 'Table\TableController@getModalDelete'));
Route::get('tables/{tables}', ['as'=> 'tables.show', 'uses' => 'Table\TableController@show']);
Route::get('tables/{tables}/edit', ['as'=> 'tables.edit', 'uses' => 'Table\TableController@edit']);

});


Route::group(array('prefix' => 'admin/reservation/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.reservation.'), function () {

Route::get('reservations', ['as'=> 'reservations.index', 'uses' => 'Reservation\ReservationController@index']);
Route::post('reservations', ['as'=> 'reservations.store', 'uses' => 'Reservation\ReservationController@store']);
Route::get('reservations/create', ['as'=> 'reservations.create', 'uses' => 'Reservation\ReservationController@create']);
Route::put('reservations/{reservations}', ['as'=> 'reservations.update', 'uses' => 'Reservation\ReservationController@update']);
Route::patch('reservations/{reservations}', ['as'=> 'reservations.update', 'uses' => 'Reservation\ReservationController@update']);
Route::get('reservations/{id}/delete', array('as' => 'reservations.delete', 'uses' => 'Reservation\ReservationController@getDelete'));
Route::get('reservations/{id}/confirm-delete', array('as' => 'reservations.confirm-delete', 'uses' => 'Reservation\ReservationController@getModalDelete'));
Route::get('reservations/{reservations}', ['as'=> 'reservations.show', 'uses' => 'Reservation\ReservationController@show']);
Route::get('reservations/{reservations}/edit', ['as'=> 'reservations.edit', 'uses' => 'Reservation\ReservationController@edit']);

});


Route::group(array('prefix' => 'admin/commande/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.commande.'), function () {

Route::get('commandes', ['as'=> 'commandes.index', 'uses' => 'Commande\CommandeController@index']);
Route::post('commandes', ['as'=> 'commandes.store', 'uses' => 'Commande\CommandeController@store']);
Route::get('commandes/create', ['as'=> 'commandes.create', 'uses' => 'Commande\CommandeController@create']);
Route::put('commandes/{commandes}', ['as'=> 'commandes.update', 'uses' => 'Commande\CommandeController@update']);
Route::patch('commandes/{commandes}', ['as'=> 'commandes.update', 'uses' => 'Commande\CommandeController@update']);
Route::get('commandes/{id}/delete', array('as' => 'commandes.delete', 'uses' => 'Commande\CommandeController@getDelete'));
Route::get('commandes/{id}/confirm-delete', array('as' => 'commandes.confirm-delete', 'uses' => 'Commande\CommandeController@getModalDelete'));
Route::get('commandes/{commandes}', ['as'=> 'commandes.show', 'uses' => 'Commande\CommandeController@show']);
Route::get('commandes/{commandes}/edit', ['as'=> 'commandes.edit', 'uses' => 'Commande\CommandeController@edit']);

});
